// =============================================================================
// TICKET STATUS
// =============================================================================
// We use a TypeScript "const object" + "keyof typeof" pattern instead of a
// traditional enum. This gives us:
//   1. A real JavaScript object at runtime (usable for iteration, labels, etc.)
//   2. A compile-time type derived from it automatically
//   3. Better compatibility with Next.js / bundlers (enums can cause issues)
// =============================================================================

export const TicketStatus = {
  OPEN: "open",
  IN_PROGRESS: "in_progress",
  RESOLVED: "resolved",
  CLOSED: "closed",
} as const;

// "typeof TicketStatus" gets the shape of the object above.
// "keyof typeof TicketStatus" gets the keys: "OPEN" | "IN_PROGRESS" | ...
// "(typeof TicketStatus)[keyof typeof TicketStatus]" gets the VALUES:
//   => "open" | "in_progress" | "resolved" | "closed"
export type TicketStatus = (typeof TicketStatus)[keyof typeof TicketStatus];

// =============================================================================
// TICKET PRIORITY
// =============================================================================
// Same pattern as TicketStatus. Priority reflects how urgently a ticket
// needs to be addressed. Having 4 levels gives teams enough granularity
// without being overwhelming.
// =============================================================================

export const TicketPriority = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
  CRITICAL: "critical",
} as const;

export type TicketPriority = (typeof TicketPriority)[keyof typeof TicketPriority];

// =============================================================================
// TICKET INTERFACE
// =============================================================================
// An "interface" describes the SHAPE of an object — what fields it has and
// what types those fields must be. TypeScript uses this at compile time only;
// it disappears completely in the final JavaScript output.
//
// Think of it as a contract: any object claiming to be a Ticket MUST have
// exactly these fields (required ones) and MAY have the optional ones (?).
// =============================================================================

// =============================================================================
// COMMENT INTERFACE  (Step 14)
// =============================================================================
// A single comment left by a user on a ticket. Comments are append-only —
// there is no edit or delete action in Phase 1 of the comment system.
//
// WHY a separate interface (not inline in Ticket)?
//   • The type can be imported independently by components (CommentList,
//     CommentForm) without importing the entire Ticket type.
//   • It can be extended in future steps (e.g. add parentId for threading)
//     without touching the Ticket interface.
//
// AUTHOR:
//   Hardcoded to "Admin" in Phase 1 (no real user management yet).
//   Phase 2: derive from the authenticated session.
// =============================================================================

export interface Comment {
  // Unique identifier — generated by generateId() in the context helper.
  id: string;

  // Display name of the comment author.
  // Hardcoded to "Admin" in Phase 1; will come from session in Phase 2.
  author: string;

  // The comment body. Always a non-empty string (validated before dispatch).
  content: string;

  // ISO 8601 timestamp — set server-side in a real app, client-side here.
  createdAt: string;
}

export interface Ticket {
  // ── Identity ──────────────────────────────────────────────────────────────
  // A unique identifier for each ticket. Using string (e.g. UUID) rather than
  // a number because UUIDs are safer across distributed systems and databases.
  id: string;

  // ── Content ───────────────────────────────────────────────────────────────
  // Short, scannable summary shown in lists and notifications.
  title: string;

  // Full explanation of the issue. Kept separate from title so the UI can
  // show just the title in compact views and expand to description on demand.
  description: string;

  // ── Categorisation ────────────────────────────────────────────────────────
  // The "?" after a field name means OPTIONAL — TypeScript won't complain if
  // this field is missing or undefined.
  category?: string;

  // An array of free-form labels (e.g. "bug", "frontend", "auth").
  // The "[]" suffix means "an array of strings".
  tags?: string[];

  // ── Lifecycle ─────────────────────────────────────────────────────────────
  // TypeScript will enforce that only valid status values can be assigned here.
  // Trying to write ticket.status = "deleted" would be a compile-time error.
  status: TicketStatus;

  // How urgently the ticket needs attention.
  priority: TicketPriority;

  // ── Ownership ─────────────────────────────────────────────────────────────
  // The user ID (or name) of whoever filed the ticket. Always required —
  // every ticket must have an author.
  createdBy: string;

  // The user ID this ticket is assigned to for resolution.
  // Optional because newly created tickets may not yet have an assignee.
  assignedTo?: string;

  // ── Timestamps ────────────────────────────────────────────────────────────
  // ISO 8601 date strings (e.g. "2026-06-12T00:00:00Z") rather than Date
  // objects — JSON serialisation (used in APIs and localStorage) does not
  // support the Date type natively; strings travel safely across boundaries.
  createdAt: string;
  updatedAt: string;

  // ── Comments  (Step 14) ───────────────────────────────────────────────────
  // Optional array so existing tickets without comments are valid.
  // The UI treats undefined the same as [] (no comments yet).
  // Persisted automatically by the existing localStorage SAVE effect.
  comments?: Comment[];
}

// =============================================================================
// UTILITY / DERIVED TYPES
// =============================================================================
// TypeScript lets you derive new types from existing ones. These are extremely
// useful so you don't have to maintain multiple parallel type definitions.
// =============================================================================

// "Omit<T, K>" creates a new type that is T with fields K removed.
// Use this when creating a new ticket — the backend/system generates id and
// timestamps, so the caller should NOT provide them.
export type CreateTicketInput = Omit<Ticket, "id" | "createdAt" | "updatedAt">;

// "Partial<T>" makes every field in T optional.
// "Pick<T, K>" selects only the fields K from T.
// Combined: a type that lets you update ONLY specific fields, all optional.
export type UpdateTicketInput = Partial<
  Pick<Ticket, "title" | "description" | "status" | "priority" | "assignedTo" | "tags" | "category">
>;

// =============================================================================
// FILTER & SORT TYPES  (added in Step 9)
// =============================================================================
// These types describe the shape of the filter bar state used on the tickets
// list page. They live here — alongside TicketStatus and TicketPriority — so
// the hook, the UI component, and any future pages all import from one place.
// =============================================================================

// "all" is a sentinel value meaning "no filter applied for this dimension".
// Using a named union (rather than undefined | TicketStatus) makes the intent
// explicit and prevents accidental comparisons against undefined.
export type StatusFilter = TicketStatus | "all";
export type PriorityFilter = TicketPriority | "all";

// SortOption encodes BOTH the sort field and direction in a single string.
// This maps 1-to-1 with the <select> options in the UI — no possibility of
// an invalid field + direction combination (e.g. sortField="title" with a
// priority-specific direction).
//
// Format convention: "<field>_<direction>"
export type SortOption =
  | "createdAt_desc"  // Newest first (default)
  | "createdAt_asc"   // Oldest first
  | "title_asc"       // Title A → Z
  | "title_desc"      // Title Z → A
  | "priority_desc"   // Priority High → Low  (critical first)
  | "priority_asc";   // Priority Low → High  (low first)

// The complete shape of one "snapshot" of the filter bar.
// The hook owns a value of this type as its state.
export interface TicketFilters {
  search: string;
  status: StatusFilter;
  priority: PriorityFilter;
  sort: SortOption;
}
